package com.joelbermudez.pocketgb.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Esquemas de contraste medio (0,5) y alto (1,0) para accesibilidad (R10). Generados con la misma semilla verde y
// la paleta terciaria azulada de los estándar (algoritmo de contraste de Material Color Utilities); colores fijos,
// sin color dinámico. Se eligen en `PocketGBTheme` según `LocalContrastLevel`.

internal val PocketLightColorScheme = lightColorScheme(
    primary = Color(0xFF3E683A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFBFF0B2),
    onPrimaryContainer = Color(0xFF002203),
    secondary = Color(0xFF53634E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD6E8CC),
    onSecondaryContainer = Color(0xFF111F0F),
    tertiary = Color(0xFF39656A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCEBF0),
    onTertiaryContainer = Color(0xFF001F22),
    background = Color(0xFFF8FAF2),
    onBackground = Color(0xFF1A1C18),
    surface = Color(0xFFF8FAF2),
    onSurface = Color(0xFF1A1C18),
    surfaceVariant = Color(0xFFDFE4D8),
    onSurfaceVariant = Color(0xFF43483F),
    outline = Color(0xFF73796E),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
)

internal val PocketDarkColorScheme = darkColorScheme(
    primary = Color(0xFFA4D398),
    onPrimary = Color(0xFF0F3912),
    primaryContainer = Color(0xFF275021),
    onPrimaryContainer = Color(0xFFBFF0B2),
    secondary = Color(0xFFBACCB1),
    onSecondary = Color(0xFF253423),
    secondaryContainer = Color(0xFF3B4B38),
    onSecondaryContainer = Color(0xFFD6E8CC),
    tertiary = Color(0xFFA0CFD4),
    onTertiary = Color(0xFF00363B),
    tertiaryContainer = Color(0xFF1F4D52),
    onTertiaryContainer = Color(0xFFBCEBF0),
    background = Color(0xFF11140F),
    onBackground = Color(0xFFE2E3DD),
    surface = Color(0xFF11140F),
    onSurface = Color(0xFFE2E3DD),
    surfaceVariant = Color(0xFF43483F),
    onSurfaceVariant = Color(0xFFC3C8BC),
    outline = Color(0xFF8D9387),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
)
internal val PocketLightMediumContrastColorScheme = lightColorScheme(
    primary = Color(0xFF274B24),
    onPrimary = Color(0xFFBAE5B0),
    primaryContainer = Color(0xFF577E51),
    onPrimaryContainer = Color(0xFFFFFFFF),
    secondary = Color(0xFF384734),
    onSecondary = Color(0xFFCDDFC5),
    secondaryContainer = Color(0xFF697964),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF1B494E),
    onTertiary = Color(0xFFB4E2E7),
    tertiaryContainer = Color(0xFF507C81),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFF8FAF2),
    onBackground = Color(0xFF1F261D),
    surface = Color(0xFFF8FAF2),
    onSurface = Color(0xFF1F261D),
    surfaceVariant = Color(0xFFDEE5D7),
    onSurfaceVariant = Color(0xFF3E453B),
    outline = Color(0xFF5A6157),
    error = Color(0xFF801F07),
    onError = Color(0xFFFFCFC4),
    errorContainer = Color(0xFFC44F34),
    onErrorContainer = Color(0xFFFFFFFF),
)

internal val PocketLightHighContrastColorScheme = lightColorScheme(
    primary = Color(0xFF052B07),
    onPrimary = Color(0xFFBAE6B0),
    primaryContainer = Color(0xFF365B32),
    onPrimaryContainer = Color(0xFFFFFFFF),
    secondary = Color(0xFF192717),
    onSecondary = Color(0xFFCDDFC6),
    secondaryContainer = Color(0xFF475643),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF00292C),
    onTertiary = Color(0xFFB4E2E8),
    tertiaryContainer = Color(0xFF2C595E),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFF8FAF2),
    onBackground = Color(0xFF000000),
    surface = Color(0xFFF8FAF2),
    onSurface = Color(0xFF000000),
    surfaceVariant = Color(0xFFDEE5D7),
    onSurfaceVariant = Color(0xFF1F261D),
    outline = Color(0xFF3E453B),
    error = Color(0xFF4C0A00),
    onError = Color(0xFFFFCFC4),
    errorContainer = Color(0xFF952E15),
    onErrorContainer = Color(0xFFFFFFFF),
)

internal val PocketDarkMediumContrastColorScheme = darkColorScheme(
    primary = Color(0xFFAFCFA6),
    onPrimary = Color(0xFF213C1E),
    primaryContainer = Color(0xFF5E7C58),
    onPrimaryContainer = Color(0xFFFFFFFF),
    secondary = Color(0xFFBACCB3),
    onSecondary = Color(0xFF2B3A28),
    secondaryContainer = Color(0xFF697964),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFFD5FAFF),
    onTertiary = Color(0xFF2C585D),
    tertiaryContainer = Color(0xFFBFEEF3),
    onTertiaryContainer = Color(0xFF235055),
    background = Color(0xFF0C0F0B),
    onBackground = Color(0xFFFFFFFF),
    surface = Color(0xFF0C0F0B),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF21281F),
    onSurfaceVariant = Color(0xFFB4BBAE),
    outline = Color(0xFF8F968A),
    error = Color(0xFFFFA089),
    onError = Color(0xFF5A0E00),
    errorContainer = Color(0xFFC44F34),
    onErrorContainer = Color(0xFFFFFFFF),
)

internal val PocketDarkHighContrastColorScheme = darkColorScheme(
    primary = Color(0xFFCDEFC3),
    onPrimary = Color(0xFF173215),
    primaryContainer = Color(0xFF8CAC85),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFFD9EBD1),
    onSecondary = Color(0xFF21301E),
    secondaryContainer = Color(0xFF97A991),
    onSecondaryContainer = Color(0xFF000000),
    tertiary = Color(0xFFD5FAFF),
    onTertiary = Color(0xFF073B40),
    tertiaryContainer = Color(0xFFBFEEF3),
    onTertiaryContainer = Color(0xFF003136),
    background = Color(0xFF0C0F0B),
    onBackground = Color(0xFFFFFFFF),
    surface = Color(0xFF0C0F0B),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF21281F),
    onSurfaceVariant = Color(0xFFE1E8DA),
    outline = Color(0xFFB4BBAE),
    error = Color(0xFFFFDED7),
    onError = Color(0xFF5A0E00),
    errorContainer = Color(0xFFFF7E5E),
    onErrorContainer = Color(0xFF000000),
)
